### ISSUE TITLE
Desktop UI design in Figma

### ISSUE THREAD

**Issue by ATMI** [IU-Capstone-Project-2024/A-Shot#10]
`feature/ui-design`
@MattWay224 

Please, create a design for desktop application in Figma. Use sketches created earlier as a starting point. Follow the Material Design 3: https://m3.material.io/

**Comment by MattWay224** [comment]
Got it. When is deadline of Lo-Fi prototype?

**Comment by ATMI** [comment]
What about Friday?

**Comment by MattWay224** [comment]
OK

**Comment by ATMI** [comment]
How is the progress? If you have any pics you can share them here))

**Comment by MattWay224** [comment]
Hey! I guess, I will share Lo-Fi prototype until today's midnight, then I want to collect feedback from our team members

**Comment by MattWay224** [comment]
And after that will create Hi-Fi prototype

**Comment by MattWay224** [comment]
I finished - https://www.figma.com/design/b8ToEj62puE2vTCj8EqwfG/Material-3-Design-Kit-(Community)?node-id=54795-26409&t=QG4IFxyQedLNHWBC-1
Want to get feedback from our team members

**Comment by ATMI** [comment]
I like it! But maybe round corners here are obsolete:

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/64b2d7d7-0e09-4e15-ab90-771449d0657e)

**Comment by MattWay224** [comment]
Got it! Thank you for the feedback. Then, I will change corners and start work on Hi-Fi prototype. You also may see progress in the same link. By the way, can you help me to find best style and colours for the dark scheme?

**Comment by MattWay224** [comment]
Hello! I finished Hi-Fi prototype 1.0, you may see it in the same link that I shared before. Moreover, this prototype is clickable, so you can see the UX

**Comment by MattWay224** [comment]
Next step is improve it with new UI and dark theme

**Comment by ATMI** [comment]
Nice design! As for now, I have noticed only few things to improve:

- Margin between the main content and a side bar

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/8edfd452-e5e1-4d7e-ac49-d22d8352be35)

- The border around right side bar is obsolete

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/202364a0-d1ec-4183-bed7-c43bbe5d3f5f)

- Some screens lack the back button for navigation to a previous screen

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/e513d850-ffed-4437-9d0f-99958eb1983a)

- No screen for import error. For example if no images found you can show the message in the same window:

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/8a2cc727-b44f-4d93-8e46-48d3dca41034)

**Comment by ATMI** [comment]
Also, maybe it makes sense to put images closer to each other, in order for easier comparison. For example here the gaps are quite big.

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/7b2c1eb3-4ec2-4bb1-a2a1-42a74f84c519)

 + imho, additional lines around the pictures might be distorting.

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/35a5eee6-a8c9-484c-887f-5d5147f9b873)

**Comment by MattWay224** [comment]
Got it, will do corrections soon

**Comment by MattWay224** [comment]
Done yesterday

**Comment by MattWay224** [comment]
For now, I can create custom icons and we can close the issue

**Comment by ATMI** [comment]
Okay, closing the issue, will open a new one for desktop development
