### ISSUE TITLE
D-DFFNet evaluation

### ISSUE THREAD

**Issue by ATMI** [IU-Capstone-Project-2024/A-Shot#12]
`feature/blur-detection`
@Post-Modern28 

Please:
- [x] Clone the repository: https://github.com/yuxinjin-whu/d-dffnet
- [x] Train the model, following the steps described in README.md
- [x] Test the model, following the README.md

Once the model is trained and is running, please contact me

**Comment by ATMI** [comment]
Have you succeeded running the model?)

**Comment by Post-Modern28** [comment]
The attempt is not successful, The model has been training the whole night and didn't finish, either I powered on cuda incorrectly or the power of my laptop is not enough and we need to move the computations on a more powerful machine, which actually would be better anyways.

**Comment by ATMI** [comment]
Please, share the project with me, I will launch it on a more suitable machine

**Comment by ATMI** [comment]
I have run the tests on my samples. The solution shows nice performance! It can even catch motion blur, but struggles to detect motion blur with pictures shot in a dark time:

![DSC_0524](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/9201a0e4-86bb-4b3d-b50f-6a3d95a31474)
![DSC_0526](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/c1e48752-6778-4d73-ac84-0f0365a571bb)
![DSC_0564](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/3c928105-af82-4d16-8ba4-2ce7ffee1bcc)
![DSC_0565](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/4e28f95e-0c6f-45a1-a2c3-cc0c618c34c4)
![DSC_0001](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/a9c7e987-85a7-4bb5-b73a-ba995624f68e)
![DSC_0149](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/2c863c6e-3a40-487d-ade9-3a0e660f3c09)
![DSC_0232](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/e2f239aa-2ed3-4e45-8b8d-afe9d16436b8)
![DSC_0256](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/e6d77fbf-ee5d-4a71-8134-de190174a3a6)
![DSC_0288](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/32aa8797-3c11-439e-9d05-81151b87a8f6)
![DSC_0429](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/1a926dac-c04e-496f-802d-451eeea4f0b6)
![DSC_0841](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/85b4b115-d272-45d8-b293-062fe69dd793)
![DSC_0987](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/90a68b21-93dd-40cd-aecf-5b8bcfae75f7)
![DSC_0016](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/1ea4284c-2353-4801-8736-2d6b249665a1)
