### ISSUE TITLE
Desktop import screens finishing

### ISSUE THREAD

**Issue by ATMI** [IU-Capstone-Project-2024/A-Shot#21]
`feature/desktop-import-screens`
@MattWay224 

Currently, desktop application contains all the required screens, but they design and functionality are not finished yet. You will be working on the loading screens group:

![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/5fc5aabf-ae54-4331-aebc-20ada2c05586)

Here are the components you will work with:

- `screen/import_/Container.kt` - this is the container element of the screen, the rounded rectangle in the center that contains all the elements on the loading screens:
 
 ![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/34af41af-ec40-4a28-a947-55d31f8f8ebb)

 There is no need to introduce new components, just fix the sizes, shapes and other style-related things:
 ```@Composable
fun <T> Container(
	state: T,
	content: @Composable BoxScope.(T) -> Unit
) {
	Box(
		// Modifier of the background
		modifier = Modifier
			.fillMaxSize()
			.background(Color.LightGray),
	) {
		Card(
			// Modifier of the central box
			modifier = Modifier
				.fillMaxSize(0.3f)
				.align(Alignment.Center),
		) {
			...
		}
	}
}
```
- `screen/import_/Select Dir.kt` - this is a single button to select the folder:
 
 ![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/b2f68129-944b-4fd9-bf9d-4d8643d5c682)

- `screen/import_/Loading.kt` - these are several elements to notify about the progress:

 ![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/ec0d592c-d408-42b3-8780-18f9f0998fdf)

 The parameters you need to display are passed as function arguments:
 ```
 @Composable
fun BoxScope.Loading(
	dirName: String,
	progress: Float,
	onCancel: () -> Unit,
) {
	...
}
 ```

- `screen/import_/Failure.kt` - this is elements for error notification:

 ![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/54db7b01-4649-4fe7-bed2-ee7c2a0cc3d5)

 As previously error message is given as function argument:
 ```
@Composable
fun BoxScope.Failure(
	reason: String,
	onOk: () -> Unit
) {
	...
}
 ```

**NOTE:** To simplify the development process each file at the bottom has a Compose Preview. To run it you need:

1. Install `Compose Multiplatform IDE Support` Plugin on your IntelliJ IDEA.
2. Restart the IDE
3. Click the Compose button on left to the function name:

 ![image](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/30948832/c5f7f59c-5dd0-4632-87a9-c28f5d53a1e2)

**Comment by ATMI** [comment]
Don't forget to checkout the branch!

**Comment by MattWay224** [comment]
Got it!

**Comment by MattWay224** [comment]
I finished with this task, you can check. If something went wrong - please contact, I'll fix
