### ISSUE TITLE
Improve UI design

### ISSUE THREAD

**Issue by ATMI** [IU-Capstone-Project-2024/A-Shot#37]
@dadagust @zDragonLORD @MattWay224 
Please create an improved Figma design, based on issues we have discussed (mainly screen wastage and too "phone-like" design). Try Material Design 2 kit.

**Comment by MattWay224** [comment]
Old version of 4photos viewer
![Frame 59](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/d89f4f4e-e83c-4616-9162-9f49694b3b6e)

new version
![Frame 42](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/a685d065-c12a-45e6-ad11-efc0a7a41549)

**Comment by MattWay224** [comment]
![Frame 42](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/318577f5-da30-4a59-81c4-3408eec6dbfb)

**Comment by MattWay224** [comment]
Updated - Numbers near every photo and selection box in number with primary color (at 1st photo)
![Frame 42](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/f850315c-d119-4f71-84d6-c1685bd61dc7)

**Comment by MattWay224** [comment]
+ variant with hiding side-bar
![Frame 42](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/7f7518d1-247a-4fa0-84ae-8c14399aa152)
![Frame 70](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/70989e97-e3f5-4f36-9d47-cc36a8f6e16d)
-Capstone-Project-2024/A-Shot/assets/112853687/c3f1bb99-3d64-4c5f-b3cb-21034f413a04)
