### ISSUE TITLE
UI design sketch

### ISSUE THREAD

**Issue by ATMI** [IU-Capstone-Project-2024/A-Shot#4]
`feature/ui-design`
@dadagust, @MattWay224, @zDragonLORD 

Please start creating UI design for desktop application:

- [x] **Define the User Flow:** User flow is the path users follow through your product to accomplish a task. Defining this helps you understand the screens you'll need to design.
- [x] **Sketch Your Ideas:** Start by sketching rough ideas on paper or a whiteboard.
- [x] **Submit:** put the user flow diagram and sketch as `design/desktop/user_flow.png` and `design/desktop/sketch.png` for the review :-)

**Comment by MattWay224** [comment]
User flow already in progress

**Comment by ATMI** [comment]
Cool! Would be nice if you finish the tasks before Tuesday)

**Comment by MattWay224** [comment]
User flow done

**Comment by ATMI** [comment]
Nice, do the sketches, I will review and close the issue

**Comment by ATMI** [comment]
Hello! Please send your sketch ideas here

**Comment by MattWay224** [comment]
![A-Shot - MattWay sketches 0 2](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/6f1f15e6-84ff-4bb0-87db-7c4a057d412f)
![A-Shot - MattWay sketches 0 1](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/583eca6a-ab8a-494f-8c95-6d305891001c)
![A-Shot - Dadagust sketches](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/714e23c1-ab49-498f-b64b-c5a8b796361c)
![A-Shot - Sketches 1 0](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/1058f1f6-8797-4b24-8056-90311ad8ef7e)
![A-Shot - MattWay sketches 0 3](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/3dd8b2ac-bbdf-461f-a42c-292f16cec11a)

**Comment by MattWay224** [comment]
![A-Shot - Sketches 1 0](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/582fa6e0-c219-4af6-a025-e92084dba9af)
![A-Shot - MattWay sketches 0 3](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/ef844191-1a4e-4f2f-9c89-7f4e5ceb015a)
![A-Shot - Dadagust sketches](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/19c5aa91-b9b4-4a5a-af55-86018c3d4063)
![A-Shot - MattWay sketches 0 2](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/eaca348f-2deb-4c7e-a672-f39f3a0865e1)
![A-Shot - MattWay sketches 0 1](https://github.com/IU-Capstone-Project-2024/A-Shot/assets/112853687/344b4101-3ee8-4545-81da-74521647ebb7)
[sketches.zip](https://github.com/user-attachments/files/15785173/sketches.zip)
