### ISSUE TITLE
Image grouping solutions research

### ISSUE THREAD

**Issue by ATMI** [IU-Capstone-Project-2024/A-Shot#5]
`feature/image-grouping`
@Shintifo, @anudammm

Please, search for existing solutions or papers on similar image grouping.

**Comment by ATMI** [comment]
You can send found links right here, I will check them as they appear :-)

**Comment by Shintifo** [comment]
Hello! After the research  we found several solutions:
1. ResNet50 model with accuracy ~81%  ([Paper](https://arxiv.org/pdf/1905.00546v1), [Weights](https://paperswithcode.com/model/resnet-semi-weakly-supervised?variant=resnet-50-semi-weakly-supervised))

2. [Image Retrieval](https://arxiv.org/pdf/1906.07589) with accuracy 60-80% on Oxford/Paris medium dataset. 

3. [ResNet101 + rating model](https://arxiv.org/pdf/1610.07940) for image retrieval with accuracy 85%.


Also we found paper that introduces [dataset](https://arxiv.org/pdf/2106.09672v4) suitable for our task.

**Comment by ATMI** [comment]
It seems that, the 1st paper is a bit off the topic, as it solves image classification problem

**Comment by ATMI** [comment]
2nd and 3rd may be nice to work with in the future. However, as we have MVP next week, have you found any papers that provide a code?

**Comment by Shintifo** [comment]
Yes, sorry for the delay. Here it is:
1. [Git](https://github.com/naver/deep-image-retrieval?tab=readme-ov-file) with both 2nd and 3rd models from my previous message

2. Another solution by Facebook team with lower accuracy ~75%([Git](https://github.com/facebookresearch/deepcluster?tab=readme-ov-file), [Paper](https://arxiv.org/pdf/2006.09882))
Also they introduced DeepClusterV2, but only [weights](https://paperswithcode.com/lib/vissl/deepclusterv2) are available.

**Comment by ATMI** [comment]
Ok, for now closing this issue, try to run the model 1 (https://github.com/naver/deep-image-retrieval?tab=readme-ov-file). Will reopen the issue after we get some valuable results for MVP.
