### ISSUE TITLE
Image loading and EXIF extraction solutions search

### ISSUE THREAD

**Issue by ATMI** [IU-Capstone-Project-2024/A-Shot#7]
`feature/image_loading`
@zDragonLORD 

To load numerous pictures in different formats, we need a fast and lightweight library. Most popular image manipulation library, OpenCV, do not fully satisfy the requirements as it has issues with RAW format, so, please find a library that:

- [x] Supports formats used by most popular camera manufacturers (Canon, Sony, Nikon, Fujifilm, and Panasonic): `.RAW`, `.NEF`, and etc.
- [x] Supports the EXIF data extraction
- [ ] Have Java and Python interfaces

Share your findings in comments!

**Comment by zDragonLORD** [comment]
[Image manipulation library.pdf](https://github.com/user-attachments/files/15784456/Image.manipulation.library.pdf)

**Comment by zDragonLORD** [comment]
[Image manipulation library.pdf](https://github.com/user-attachments/files/15784502/Image.manipulation.library.pdf)

**Comment by dadagust** [comment]
better to search for a solution, that provides a bitmap of an image

**Comment by ATMI** [comment]
It's not a problem. The most important that the library gives you data in some interpretable format. After that, for example, in Java you can use BitmapFactory.decodeX or other methods

**Comment by ATMI** [comment]
@zDragonLORD, ImageMagick sounds like an option. However, could you look for libraries that can extract images and EXIF data from various formats once more, but the only limitation now is that the library should be written in C/C++?

**Comment by zDragonLORD** [comment]
[Image manipulation library C.pdf](https://github.com/user-attachments/files/15804634/Image.manipulation.library.C.pdf)

**Comment by ATMI** [comment]
Thanks, will check a bit later!

**Comment by ATMI** [comment]
Thx, we will use ImageMagick, closing the issue!
